### ISSUE TITLE
Where wallpaper?

### ISSUE THREAD

**Issue by mTvare6** [Aerdian/atlas-dotfiles#1]

**Comment by Aerdian** [comment]
Hello! Thanks for your interest. I have added the wallpaper to the repository [here](https://github.com/Aerdian/atlas-dotfiles/blob/main/wallpaper.jpg). Alternatively, I attached the wallpaper below.

![wallpaper](https://user-images.githubusercontent.com/30437001/118152232-14e92c00-b3da-11eb-84ef-f8a62505ac47.jpg)
